/// Class Name: mClarkAssignment1Cylinder.CylinderForm
/// Class Description: Auto-generated by Windows Form Designer
/// Developer Name: Mary Clark
/// Date Created: 9/9/2018
/// Date Last Modified: 9/9/2018
///
namespace mClarkAssignment1Cylinder
{
    partial class CylinderForm
    {
        ///
        /// Required designer variable.
        ///
        private System.ComponentModel.IContainer components = null;

        /// 
        /// Clean up any resources being used.
        /// 
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        ///
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.lblRadius = new System.Windows.Forms.Label();
            this.lblHeight = new System.Windows.Forms.Label();
            this.tboxRadiusMask = new System.Windows.Forms.MaskedTextBox();
            this.tboxHeightMask = new System.Windows.Forms.MaskedTextBox();
            this.btnArea = new System.Windows.Forms.Button();
            this.btnVolume = new System.Windows.Forms.Button();
            this.lblResult = new System.Windows.Forms.Label();
            this.btnExit = new System.Windows.Forms.Button();
            this.lblDev = new System.Windows.Forms.Label();
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.errorProvider2 = new System.Windows.Forms.ErrorProvider(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider2)).BeginInit();
            this.SuspendLayout();
            // 
            // lblRadius
            // 
            this.lblRadius.AutoSize = true;
            this.lblRadius.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblRadius.Location = new System.Drawing.Point(48, 88);
            this.lblRadius.Name = "lblRadius";
            this.lblRadius.Size = new System.Drawing.Size(240, 16);
            this.lblRadius.TabIndex = 0;
            this.lblRadius.Text = "Enter the radius of the cylinder in inches";
            // 
            // lblHeight
            // 
            this.lblHeight.AutoSize = true;
            this.lblHeight.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblHeight.Location = new System.Drawing.Point(48, 144);
            this.lblHeight.Name = "lblHeight";
            this.lblHeight.Size = new System.Drawing.Size(239, 16);
            this.lblHeight.TabIndex = 1;
            this.lblHeight.Text = "Enter the height of the cylinder in inches";
            // 
            // tboxRadiusMask
            // 
            this.tboxRadiusMask.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tboxRadiusMask.Location = new System.Drawing.Point(304, 83);
            this.tboxRadiusMask.Mask = "00000";
            this.tboxRadiusMask.Name = "tboxRadiusMask";
            this.tboxRadiusMask.Size = new System.Drawing.Size(50, 26);
            this.tboxRadiusMask.TabIndex = 2;
            this.tboxRadiusMask.ValidatingType = typeof(int);
            this.tboxRadiusMask.MaskInputRejected += new System.Windows.Forms.MaskInputRejectedEventHandler(this.TboxRadiusMask_MaskInputRejected);
            // 
            // tboxHeightMask
            // 
            this.tboxHeightMask.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tboxHeightMask.Location = new System.Drawing.Point(304, 139);
            this.tboxHeightMask.Mask = "00000";
            this.tboxHeightMask.Name = "tboxHeightMask";
            this.tboxHeightMask.Size = new System.Drawing.Size(50, 26);
            this.tboxHeightMask.TabIndex = 3;
            this.tboxHeightMask.ValidatingType = typeof(int);
            this.tboxHeightMask.MaskInputRejected += new System.Windows.Forms.MaskInputRejectedEventHandler(this.TboxHeightMask_MaskInputRejected);
            // 
            // btnArea
            // 
            this.btnArea.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnArea.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnArea.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnArea.Location = new System.Drawing.Point(48, 192);
            this.btnArea.Name = "btnArea";
            this.btnArea.Size = new System.Drawing.Size(75, 32);
            this.btnArea.TabIndex = 4;
            this.btnArea.Text = "Area";
            this.btnArea.UseVisualStyleBackColor = false;
            this.btnArea.Click += new System.EventHandler(this.BtnArea_Click);
            // 
            // btnVolume
            // 
            this.btnVolume.BackColor = System.Drawing.SystemColors.ControlDark;
            this.btnVolume.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnVolume.Location = new System.Drawing.Point(48, 240);
            this.btnVolume.Name = "btnVolume";
            this.btnVolume.Size = new System.Drawing.Size(75, 32);
            this.btnVolume.TabIndex = 5;
            this.btnVolume.Text = "Volume";
            this.btnVolume.UseVisualStyleBackColor = false;
            this.btnVolume.Click += new System.EventHandler(this.BtnVolume_Click);
            // 
            // lblResult
            // 
            this.lblResult.AutoSize = true;
            this.lblResult.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblResult.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblResult.Location = new System.Drawing.Point(176, 216);
            this.lblResult.MinimumSize = new System.Drawing.Size(100, 26);
            this.lblResult.Name = "lblResult";
            this.lblResult.Size = new System.Drawing.Size(100, 26);
            this.lblResult.TabIndex = 6;
            // 
            // btnExit
            // 
            this.btnExit.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnExit.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExit.Location = new System.Drawing.Point(296, 288);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(75, 32);
            this.btnExit.TabIndex = 7;
            this.btnExit.Text = "Exit";
            this.btnExit.UseVisualStyleBackColor = true;
            this.btnExit.Click += new System.EventHandler(this.BtnExit_Click);
            // 
            // lblDev
            // 
            this.lblDev.AutoSize = true;
            this.lblDev.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.lblDev.Location = new System.Drawing.Point(248, 328);
            this.lblDev.Name = "lblDev";
            this.lblDev.Size = new System.Drawing.Size(126, 13);
            this.lblDev.TabIndex = 8;
            this.lblDev.Text = "Developed by Mary Clark";
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // errorProvider2
            // 
            this.errorProvider2.ContainerControl = this;
            // 
            // CylinderForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.btnExit;
            this.ClientSize = new System.Drawing.Size(398, 353);
            this.Controls.Add(this.lblDev);
            this.Controls.Add(this.btnExit);
            this.Controls.Add(this.lblResult);
            this.Controls.Add(this.btnVolume);
            this.Controls.Add(this.btnArea);
            this.Controls.Add(this.tboxHeightMask);
            this.Controls.Add(this.tboxRadiusMask);
            this.Controls.Add(this.lblHeight);
            this.Controls.Add(this.lblRadius);
            this.Name = "CylinderForm";
            this.Text = "Calculate Cylinder";
            this.Load += new System.EventHandler(this.CylinderForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider2)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lblRadius;
        private System.Windows.Forms.Label lblHeight;
        private System.Windows.Forms.MaskedTextBox tboxRadiusMask;
        private System.Windows.Forms.MaskedTextBox tboxHeightMask;
        private System.Windows.Forms.Button btnArea;
        private System.Windows.Forms.Button btnVolume;
        private System.Windows.Forms.Label lblResult;
        private System.Windows.Forms.Button btnExit;
        private System.Windows.Forms.Label lblDev;
        private System.Windows.Forms.ErrorProvider errorProvider1;
        private System.Windows.Forms.ErrorProvider errorProvider2;
    }
}

