/// Class Name: mClarkAssignment1.FrmMovie
/// Class Description: The FrmMovie class is the presentation layer of the Movie class. 
/// It contains the constructor for
/// the FrmMovie class and the event handlers for the controls on the form.
/// Developer Name: Mary Clark
/// Date Created: 9/2/2018
/// Date Last Modified: 9/9/2018

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace mClarkAssignment1
{
    public partial class FrmMovie : Form
    {
        /// 
        /// The Constructor for the FrmMovie Form class
        /// 
        public FrmMovie()
        {
            InitializeComponent();
        }
        /// 
        /// The event handler for the btnActor control.
        /// When btnActor receives a click event,
        /// instantiate a new Movie object and call
        /// the Movie object's ShowLeadActor method to
        /// populate the lblActorResult box on the movie form.
        ///
        private void BtnActor_Click(object sender, EventArgs e)
        {
            Movie aMovie = new Movie();
            lblActorResult.Text = aMovie.ShowLeadActor();
            ///
            /// Note that since the result is static, we could
            /// skip creating a new Movie object and simply
            /// set the result to the literal string. 
            /// However, that leaves us with no method for
            /// deriving different results, and violates
            /// good OOP modular design practice.
            ///
            /// lblActorResult.Text = "Burt Reynolds";
            ///
        }
        /// 
        /// The event handler for the btnActress control.
        /// When btnActress receives a click event,
        /// instantiate a new Movie object and call
        /// the Movie object's ShowLeadActress method to
        /// populate the lblActressResult box on the movie form.
        ///
        private void BtnActress_Click(object sender, EventArgs e)
        {
            Movie aMovie = new Movie();
            lblActressResult.Text = aMovie.ShowLeadActress();
        }
        /// 
        /// The event handler for the btnDirector control.
        /// When btnDirector receives a click event,
        /// instantiate a new Movie object and call
        /// the Movie object's ShowDirector method to
        /// populate the lblDirectorResult box on the movie form.
        ///
        private void BtnDirector_Click(object sender, EventArgs e)
        {
            Movie aMovie = new Movie();
            lblDirectorResult.Text = aMovie.ShowDirector();
        }
        /// 
        /// The event handler for the btnExit control terminates
        /// the program.
        ///
        private void BtnExit_Click(object sender, EventArgs e)
        {
            this.Close();
        }
        ///
        /// Autogenerated method. Load the form.
        /// 
        private void FrmMovie_Load(object sender, EventArgs e)
        {

        }
    }
}
