package subnet;

import java.awt.Color;
import java.text.NumberFormat;
import java.text.ParseException;

public class Frame extends javax.swing.JFrame {

    static CalcSubnets nc = new CalcSubnets();
    static NumberFormat nf = NumberFormat.getIntegerInstance();
    int inum0, inum1, inum2, inum3, pnum0, pnum1, pnum2, pnum3, snum0, snum1, snum2, snum3;
    int next = 0;

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIPAddr = new javax.swing.JLabel();
        lblBOctets = new javax.swing.JLabel();
        lblBin1 = new javax.swing.JLabel();
        lblBin2 = new javax.swing.JLabel();
        lblBin3 = new javax.swing.JLabel();
        lblBin4 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        lblClass = new javax.swing.JLabel();
        lblMask1 = new javax.swing.JLabel();
        lblMask2 = new javax.swing.JLabel();
        lblMask3 = new javax.swing.JLabel();
        lblMask4 = new javax.swing.JLabel();
        txtOctet1 = new javax.swing.JTextField();
        txtOctet2 = new javax.swing.JTextField();
        txtOctet3 = new javax.swing.JTextField();
        txtOctet4 = new javax.swing.JTextField();
        lblPBin1 = new javax.swing.JLabel();
        lblPBin2 = new javax.swing.JLabel();
        lblPBin3 = new javax.swing.JLabel();
        lblPBin4 = new javax.swing.JLabel();
        lblPNetmask = new javax.swing.JLabel();
        lblPrimaryNetmask = new javax.swing.JLabel();
        txtMaskP1 = new javax.swing.JTextField();
        txtMaskP2 = new javax.swing.JTextField();
        txtMaskP3 = new javax.swing.JTextField();
        txtMaskP4 = new javax.swing.JTextField();
        lblSubnetmask1 = new javax.swing.JLabel();
        txtMaskS1 = new javax.swing.JTextField();
        txtMaskS2 = new javax.swing.JTextField();
        txtMaskS3 = new javax.swing.JTextField();
        txtMaskS4 = new javax.swing.JTextField();
        lblSubnetmask2 = new javax.swing.JLabel();
        lblSBin1 = new javax.swing.JLabel();
        lblSBin2 = new javax.swing.JLabel();
        lblSBin3 = new javax.swing.JLabel();
        lblSBin4 = new javax.swing.JLabel();
        lblErrorMsg = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 25), new java.awt.Dimension(3, 25), new java.awt.Dimension(3, 25));
        jPanel2 = new javax.swing.JPanel();
        lblSlashIP = new javax.swing.JLabel();
        lblSlashPrimary = new javax.swing.JLabel();
        lblSlashClass = new javax.swing.JLabel();
        lblSlashSubnet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Network Config");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Network", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPanel1.setName(""); // NOI18N

        lblIPAddr.setText("IP Address");

        lblBOctets.setText("Binary IP");

        lblBin1.setText("0000 0000");
        lblBin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblBin2.setText("0000 0000");
        lblBin2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblBin3.setText("0000 0000");
        lblBin3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblBin4.setText("0000 0000");
        lblBin4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnOK.setText("Ok");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        lblClass.setText("Prefix Class");
        lblClass.setToolTipText("");
        lblClass.setEnabled(false);

        lblMask1.setText("0000 0000");
        lblMask1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblMask1.setEnabled(false);

        lblMask2.setText("0000 0000");
        lblMask2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblMask2.setEnabled(false);

        lblMask3.setText("0000 0000");
        lblMask3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblMask3.setEnabled(false);

        lblMask4.setText("0000 0000");
        lblMask4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblMask4.setEnabled(false);

        txtOctet1.setColumns(3);

        txtOctet2.setColumns(3);

        txtOctet3.setColumns(3);

        txtOctet4.setColumns(3);

        lblPBin1.setText("0000 0000");
        lblPBin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPBin2.setText("0000 0000");
        lblPBin2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPBin3.setText("0000 0000");
        lblPBin3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPBin4.setText("0000 0000");
        lblPBin4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPNetmask.setText("Primary Netmask");

        lblPrimaryNetmask.setText("Primary Netmask");

        txtMaskP1.setColumns(3);

        txtMaskP2.setColumns(3);

        txtMaskP3.setColumns(3);

        txtMaskP4.setColumns(3);
        txtMaskP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaskP4ActionPerformed(evt);
            }
        });

        lblSubnetmask1.setText("Subnet Mask");

        txtMaskS1.setColumns(3);

        txtMaskS2.setColumns(3);

        txtMaskS3.setColumns(3);

        txtMaskS4.setColumns(3);
        txtMaskS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaskS4ActionPerformed(evt);
            }
        });

        lblSubnetmask2.setText("Subnet Mask");

        lblSBin1.setText("0000 0000");
        lblSBin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSBin1.setFocusable(false);
        lblSBin1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblSBin2.setText("0000 0000");
        lblSBin2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSBin3.setText("0000 0000");
        lblSBin3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSBin4.setText("0000 0000");
        lblSBin4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblErrorMsg.setForeground(new java.awt.Color(255, 51, 0));
        lblErrorMsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblErrorMsg.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblErrorMsg.setMaximumSize(new java.awt.Dimension(250, 100));
        lblErrorMsg.setMinimumSize(new java.awt.Dimension(100, 50));
        lblErrorMsg.setName(""); // NOI18N
        lblErrorMsg.setPreferredSize(new java.awt.Dimension(100, 50));
        lblErrorMsg.setVerifyInputWhenFocusTarget(false);

        btnReset.setText("Reset");
        btnReset.setToolTipText("");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSlashIP)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblSlashIP)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        lblSlashPrimary.setText("/");

        lblSlashClass.setText("/");
        lblSlashClass.setToolTipText("");

        lblSlashSubnet.setText("/");

        lblErrorMsg.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIPAddr)
                    .addComponent(lblPrimaryNetmask)
                    .addComponent(lblSubnetmask1))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtOctet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtOctet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtOctet3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtOctet4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMaskP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtMaskP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtMaskP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtMaskP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMaskS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtMaskS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtMaskS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtMaskS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblBOctets, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPNetmask, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblSubnetmask2, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMask1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMask2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMask3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMask4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblBin1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblBin2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblBin3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblBin4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblPBin1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblPBin2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblPBin3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblPBin4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblSBin1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblSBin2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblSBin3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblSBin4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSlashClass, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lblSlashPrimary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSlashSubnet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuit)
                .addGap(6, 6, 6))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBin1, lblBin2, lblBin3, lblBin4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClass)
                            .addComponent(lblMask1)
                            .addComponent(lblMask2)
                            .addComponent(lblMask3)
                            .addComponent(lblMask4)
                            .addComponent(lblSlashClass))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIPAddr)
                            .addComponent(txtOctet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOctet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOctet3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOctet4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBOctets)
                            .addComponent(lblBin1)
                            .addComponent(lblBin2)
                            .addComponent(lblBin3)
                            .addComponent(lblBin4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrimaryNetmask)
                            .addComponent(txtMaskP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaskP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaskP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaskP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPNetmask)
                            .addComponent(lblPBin1)
                            .addComponent(lblPBin2)
                            .addComponent(lblPBin3)
                            .addComponent(lblPBin4)
                            .addComponent(lblSlashPrimary))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubnetmask1)
                            .addComponent(txtMaskS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaskS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaskS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaskS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubnetmask2)
                            .addComponent(lblSBin1)
                            .addComponent(lblSBin2)
                            .addComponent(lblSBin3)
                            .addComponent(lblSBin4)
                            .addComponent(lblSlashSubnet)))
                    .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOK)
                            .addComponent(btnQuit)
                            .addComponent(btnReset)))
                    .addComponent(lblErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBin1, lblBin2, lblBin3, lblBin4});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        lblErrorMsg.setText("");
        lblErrorMsg.setVisible(false);
        lblSlashClass.setText("/");
        lblSlashPrimary.setText("/");
        lblSlashSubnet.setText("/");

        txtOctet1.setBackground(Color.WHITE);
        txtOctet2.setBackground(Color.WHITE);
        txtOctet3.setBackground(Color.WHITE);
        txtOctet4.setBackground(Color.WHITE);
        txtMaskP1.setBackground(Color.WHITE);
        txtMaskP2.setBackground(Color.WHITE);
        txtMaskP3.setBackground(Color.WHITE);
        txtMaskP4.setBackground(Color.WHITE);
        txtMaskS1.setBackground(Color.WHITE);
        txtMaskS2.setBackground(Color.WHITE);
        txtMaskS3.setBackground(Color.WHITE);
        txtMaskS4.setBackground(Color.WHITE);

        lblBin1.setText("0000 0000");
        lblBin2.setText("0000 0000");
        lblBin3.setText("0000 0000");
        lblBin4.setText("0000 0000");
        lblClass.setText("");
        lblMask1.setText("0000 0000");
        lblMask2.setText("0000 0000");
        lblMask3.setText("0000 0000");
        lblMask4.setText("0000 0000");
        lblPBin1.setText("0000 0000");
        lblPBin2.setText("0000 0000");
        lblPBin3.setText("0000 0000");
        lblPBin4.setText("0000 0000");
        lblSBin1.setText("0000 0000");
        lblSBin2.setText("0000 0000");
        lblSBin3.setText("0000 0000");
        lblSBin4.setText("0000 0000");
        txtMaskP1.setText("");
        txtMaskP2.setText("");
        txtMaskP3.setText("");
        txtMaskP4.setText("");
        txtMaskS1.setText("");
        txtMaskS2.setText("");
        txtMaskS3.setText("");
        txtMaskS4.setText("");
        txtOctet1.setText("");
        txtOctet2.setText("");
        txtOctet3.setText("");
        txtOctet4.setText("");
        inum0 = 0;
        inum1 = 0;
        inum2 = 0;
        inum3 = 0;
        pnum0 = 0;
        pnum1 = 0;
        pnum2 = 0;
        pnum3 = 0;
        snum0 = 0;
        snum1 = 0;
        snum2 = 0;
        snum3 = 0;
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtMaskS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaskS4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaskS4ActionPerformed

    private void txtMaskP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaskP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaskP4ActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed

        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        int primarySlash = 0;
        int subnetSlash = 0;

        txtOctet1.setBackground(Color.WHITE);
        txtOctet2.setBackground(Color.WHITE);
        txtOctet3.setBackground(Color.WHITE);
        txtOctet4.setBackground(Color.WHITE);
        txtMaskP1.setBackground(Color.WHITE);
        txtMaskP2.setBackground(Color.WHITE);
        txtMaskP3.setBackground(Color.WHITE);
        txtMaskP4.setBackground(Color.WHITE);
        txtMaskS1.setBackground(Color.WHITE);
        txtMaskS2.setBackground(Color.WHITE);
        txtMaskS3.setBackground(Color.WHITE);
        txtMaskS4.setBackground(Color.WHITE);
        lblErrorMsg.setText("");
        lblErrorMsg.setVisible(false);
        String whatFailed = "initial";
        try {
            nf.setMinimumIntegerDigits(1);
            nf.setMaximumIntegerDigits(3);
            String[] nibbles = new String[4];
            boolean validInput=true;
            whatFailed = "initial0";
            inum0 = nf.parse(txtOctet1.getText()).intValue();
            whatFailed = "initial1";
            inum1 = nf.parse(txtOctet2.getText()).intValue();
            whatFailed = "initial2";
            inum2 = nf.parse(txtOctet3.getText()).intValue();
            whatFailed = "initial3";
            inum3 = nf.parse(txtOctet4.getText()).intValue();
            whatFailed = "";
            validInput=validateInput(inum0, inum1, inum2, inum3, "initial");
            if (validInput) {
                nc.setOctet(inum0, 0,"initial");
                nc.setOctet(inum1, 1,"initial");
                nc.setOctet(inum2, 2,"initial");
                nc.setOctet(inum3, 3,"initial");
                nibbles = nc.getNibbles("initial");

                lblBin1.setText(nibbles[0]);
                lblBin2.setText(nibbles[1]);
                lblBin3.setText(nibbles[2]);
                lblBin4.setText(nibbles[3]);
            }

            if (!txtMaskP1.getText().isEmpty()) {
                whatFailed = "primary0";
                pnum0 = nf.parse(txtMaskP1.getText()).intValue();
                whatFailed = "primary1";
                pnum1 = nf.parse(txtMaskP2.getText()).intValue();
                whatFailed = "primary2";
                pnum2 = nf.parse(txtMaskP3.getText()).intValue();
                whatFailed = "primary3";
                pnum3 = nf.parse(txtMaskP4.getText()).intValue();
                validInput=validateInput(pnum0, pnum1, pnum2, pnum3, "primary");
                if (validInput) {
                    nc.setOctet(pnum0, 0,"primary");
                    nc.setOctet(pnum1, 1,"primary");
                    nc.setOctet(pnum2, 2,"primary");
                    nc.setOctet(pnum3, 3,"primary");
                    nibbles = nc.getNibbles("primary");
                    String showIt = "";
                    String colorIt = "";
                    String sub = "";

                    int j = 0;
                    int i = 0;
                    for(i=0;i<4;i++) {
                        for (j = 0; j<9; j++) {
                            if (nibbles[i].charAt(j) == '1' || nibbles[i].charAt(j) == ' ') {
                                if (nibbles[i].charAt(j) == '1')
                                primarySlash++;
                                continue;
                                //sub = nibbles[i].substring(0,j);
                                //colorIt = "<html><font color=red>" + sub + "</font>";
                            } else break;
                        }
                        sub = nibbles[i].substring(0,j);
                        colorIt = "<html><font color=red>"+sub+"</font>";
                        showIt = colorIt + nibbles[i].substring(j);
                        if(i == 0) {
                            lblPBin1.setText(showIt);

                            continue;
                        }
                        if (i == 1) {
                            lblPBin2.setText(showIt);
                            continue;
                        }
                        if (i == 2) {
                            lblPBin3.setText(showIt);
                            continue;
                        }
                        if (i == 3) {
                            lblPBin4.setText(showIt);
                            continue;
                        }
                    }
                    lblSlashPrimary.setText("/"+primarySlash);
                    //lblPBin1.setText(nibbles[0]);
                    //lblPBin2.setText(nibbles[1]);
                    //lblPBin3.setText(nibbles[2]);
                    //lblPBin4.setText(nibbles[3]);

                }
            }
            if (!txtMaskS1.getText().isEmpty()) {
                whatFailed = "subnet0";
                snum0 = nf.parse(txtMaskS1.getText()).intValue();
                whatFailed = "subnet1";
                snum1 = nf.parse(txtMaskS2.getText()).intValue();
                whatFailed = "subnet2";
                snum2 = nf.parse(txtMaskS3.getText()).intValue();
                whatFailed = "subnet3";
                snum3 = nf.parse(txtMaskS4.getText()).intValue();
                validInput = validateInput(snum0, snum1, snum2, snum3, "subnet");
                if (validInput) {
                    nc.setOctet(snum0, 0,"subnet");
                    nc.setOctet(snum1, 1,"subnet");
                    nc.setOctet(snum2, 2,"subnet");
                    nc.setOctet(snum3, 3,"subnet");
                    nibbles = nc.getNibbles("subnet");

                    String showIt = "";
                    String colorIt = "";
                    String sub = "";
                    int j = 0;
                    int i = 0;
                    for(i=0;i<4;i++) {
                        for (j = 0; j<9; j++) {
                            if (nibbles[i].charAt(j) == '1' || nibbles[i].charAt(j) == ' ') {
                                if (nibbles[i].charAt(j) == '1')
                                subnetSlash++;
                                continue;
                                //sub = nibbles[i].substring(0,j);
                                //colorIt = "<html><font color=red>" + sub + "</font>";
                            } else break;
                        }
                        sub = nibbles[i].substring(0,j);
                        colorIt = "<html><font color=blue>"+sub+"</font>";
                        showIt = colorIt + nibbles[i].substring(j);

                        if(i == 0) {
                            lblSBin1.setText(showIt);
                            System.out.println("lblPBin1:" + lblPBin1.getText());
                            System.out.println("lblSBin1:" + lblSBin1.getText());
                            continue;
                        }
                        if (i == 1) {
                            lblSBin2.setText(showIt);
                            System.out.println("lblPBin2:" + lblPBin2.getText());
                            System.out.println("lblSBin2:" + lblSBin2.getText());
                            continue;
                        }
                        if (i == 2) {
                            lblSBin3.setText(showIt);
                            System.out.println("lblPBin3:" + lblPBin3.getText());
                            System.out.println("lblSBin3:" + lblSBin3.getText());
                            continue;
                        }
                        if (i == 3) {
                            lblSBin4.setText(showIt);
                            System.out.println("lblPBin4:" + lblPBin4.getText());
                            System.out.println("lblSBin4:" + lblSBin4.getText());
                            continue;
                        }
                    }
                    lblSlashSubnet.setText("/"+ subnetSlash);
                    //lblSBin1.setText(nibbles[0]);
                    //lblSBin2.setText(nibbles[1]);
                    //lblSBin3.setText(nibbles[2]);
                    //lblSBin4.setText(nibbles[3]);
                }
            }
            if (!validInput) {
                lblErrorMsg.setVisible(true);
                return;
            }
        } catch (NumberFormatException | ParseException e) {
            if (whatFailed.equals("initial0"))
            txtOctet1.setBackground(Color.red);
            if (whatFailed.equals("initial1"))
            txtOctet2.setBackground(Color.red);
            if (whatFailed.equals("initial2"))
            txtOctet3.setBackground(Color.red);
            if (whatFailed.equals("initial3"))
            txtOctet4.setBackground(Color.red);
            if (whatFailed.equals("primary0"))
            txtMaskP1.setBackground(Color.red);
            if (whatFailed.equals("primary1"))
            txtMaskP2.setBackground(Color.red);
            if (whatFailed.equals("primary2"))
            txtMaskP3.setBackground(Color.red);
            if (whatFailed.equals("primary3"))
            txtMaskP4.setBackground(Color.red);
            if (whatFailed.equals("subnet0"))
            txtMaskS1.setBackground(Color.red);
            if (whatFailed.equals("subnet1"))
            txtMaskS2.setBackground(Color.red);
            if (whatFailed.equals("subnet2"))
            txtMaskS3.setBackground(Color.red);
            if (whatFailed.equals("subnet3"))
            txtMaskS4.setBackground(Color.red);
            lblErrorMsg.setText(e.getMessage());
            lblErrorMsg.setVisible(true);
            System.out.println("whatfailed = " + whatFailed);
            System.out.println("e.getMessage = " + e.getMessage());
            System.out.println("e.toString = " + e.toString());
            return;
        }
        char pClass = nc.getNetworkPrefixClass();
        String classString = new String();
        lblClass.setEnabled(true);
        lblClass.setVisible(true);
        if (pClass == 'R') {
            lblClass.setText("IP Prefix is RESERVED");
        } else {
            lblClass.setText("IP Prefix is Class " + pClass);
            lblClass.setEnabled(true);
        }
        classString = lblBin1.getText();

        if (pClass == 'A') {
            String sub = classString.substring(0,1);
            String colorIt = "<html><font color=red>" + sub + "</font>";
            classString = colorIt + classString.substring(1);
            lblBin1.setText(classString);
            lblSlashClass.setText("/8");
        }
        if (pClass == 'B') {
            String sub = classString.substring(0,2);
            String colorIt = "<html><font color=red>" + sub + "</font>";
            classString = colorIt + classString.substring(2);
            lblBin1.setText(classString);
            lblSlashClass.setText("/16");
        }
        if (pClass == 'C') {
            String sub = classString.substring(0,2);
            String colorIt = "<html><font color=red>" + sub + "</font>";
            classString = colorIt + classString.substring(2);
            lblBin1.setText(classString);
            lblSlashClass.setText("/24");
        }
        if (pClass == 'R') {
            String sub = classString.substring(0,3);
            String colorIt = "<html><font color=red>" + sub + "</font>";
            classString = colorIt + classString.substring(3);
            lblBin1.setText(classString);
            lblSlashClass.setText("");
        }
        lblMask1.setText(nc.getClassNetMaskNibble(0));
        lblMask1.setEnabled(true);
        lblMask2.setText(nc.getClassNetMaskNibble(1));
        lblMask2.setEnabled(true);
        lblMask3.setText(nc.getClassNetMaskNibble(2));
        lblMask3.setEnabled(true);
        lblMask4.setText(nc.getClassNetMaskNibble(3));
        lblMask4.setEnabled(true);
        lblSlashClass.setEnabled(true);
    }//GEN-LAST:event_btnOKActionPerformed

    private boolean validateInput(int num0, int num1, int num2, int num3, String type) {
        boolean valid = true;
        if (type.equals("initial")) {
            if (num0 > 255 || num0 < 0) {
                txtOctet1.setBackground(Color.red);
                lblErrorMsg.setText("IP address numbers must be in the range of 0 to 255");
                valid = false;
            }
            if (num1 > 255 || num1 < 0) {
                txtOctet2.setBackground(Color.red);
                lblErrorMsg.setText("IP address numbers must be in the range of 0 to 255");
                valid = false;
            }
            if (num2 > 255 || num2 < 0) {
                txtOctet3.setBackground(Color.red);
                lblErrorMsg.setText("IP address numbers must be in the range of 0 to 255");
                valid = false;
            }
            if (num3 > 255 || num3 < 0) {
                txtOctet4.setBackground(Color.red);
                lblErrorMsg.setText("IP address numbers must be in the range of 0 to 255");
                valid = false;
            }
        }
        if (type.equals("primary")) {
            if (num0 > 255 || num0 < 0) {
                txtMaskP1.setBackground(Color.red);
                lblErrorMsg.setText("IP address numbers must be in the range of 0 to 255.");
                valid = false;
            }
            else if (!validateMask(num0)) {
                txtMaskP1.setBackground(Color.red);
                valid = false;
                lblErrorMsg.setText("Netmask bits must be contiguous 1's. Next valid mask number is " + next);
            }

            if (num1 > 255 || num1 < 0) {
              txtMaskP2.setBackground(Color.red);
              lblErrorMsg.setText("IP address numbers must be in the range of 0 to 255");
                valid = false;
            }
            else if (!validateMask(num1)) {
                txtMaskP2.setBackground(Color.red);
                valid = false;
                lblErrorMsg.setText("Netmask bits must be contiguous 1's. Next valid mask number is " + next);
            }
            if (num2 > 255 || num2 < 0) {
                txtMaskP3.setBackground(Color.red);
                lblErrorMsg.setText("IP address numbers must be in the range of 0 to 255");
                valid = false;
            }
            else if (!validateMask(num2)) {
                txtMaskP3.setBackground(Color.red);
                valid = false;
                lblErrorMsg.setText("Netmask bits must be contiguous 1's. Next valid mask number is " + next);
            }
            if (num3 > 255 || num3 < 0) {
                txtMaskP4.setBackground(Color.red);
                lblErrorMsg.setText("IP address numbers must be in the range of 0 to 255");
                valid = false;
            } else if (!validateMask(num3)) {
                txtMaskP4.setBackground(Color.red);
                valid = false;
                lblErrorMsg.setText("Netmask bits must be contiguous 1's. Next valid mask number is " + next);
            }
        }
        if (type.equals("subnet")) {
            if (num0 > 255 || num0 < 0) {
                txtMaskS1.setBackground(Color.red);
                lblErrorMsg.setText("IP address numbers must be in the range of 0 to 255");
                valid = false;
            } else if (num0 < pnum0) {
                txtMaskS1.setBackground(Color.red);
                lblErrorMsg.setText("Subnet cannot be larger than parent network.");
                valid = false;
            } else if (!validateMask(num0)) {
                txtMaskS1.setBackground(Color.red);
                valid = false;
                lblErrorMsg.setText("Netmask bits must be contiguous 1's. Next valid mask number is " + next);
            }
            if (num1 > 255 || num1 < 0) {
              txtMaskS2.setBackground(Color.red);
              lblErrorMsg.setText("IP address numbers must be in the range of 0 to 255");
                valid = false;
            } else if(num1 < pnum1) {
                txtMaskS2.setBackground(Color.red);
                lblErrorMsg.setText("Subnet cannot be larger than parent network.");
                valid = false;
            } else if (!validateMask(num1)) {
                txtMaskS2.setBackground(Color.red);
                valid = false;
                lblErrorMsg.setText("Netmask bits must be contiguous 1's. Next valid mask number is " + next);
            }

            if (num2 > 255 || num2 < 0) {
                txtMaskS3.setBackground(Color.red);
                lblErrorMsg.setText("IP address numbers must be in the range of 0 to 255");
                valid = false;
            } else if (num2 < pnum2) {
                txtMaskS3.setBackground(Color.red);
                lblErrorMsg.setText("Subnet cannot be larger than parent network.");
                valid = false;
            } else if (!validateMask(num2)) {
                txtMaskS3.setBackground(Color.red);
                valid = false;
                lblErrorMsg.setText("Netmask bits must be contiguous 1's. Next valid mask number is " + next );
            }
            if (num3 > 255 || num3 < 0) {
                txtMaskS4.setBackground(Color.red);
                lblErrorMsg.setText("IP address numbers must be in the range of 0 to 255");
                valid = false;
            } else if (num3 < pnum3) {
                txtMaskS3.setBackground(Color.red);
                lblErrorMsg.setText("Subnet cannot be larger than parent network.");
                valid = false;
            } else if (!validateMask(num3)) {
                txtMaskS4.setBackground(Color.red);
                valid = false;
                lblErrorMsg.setText("Netmask bits must be contiguous 1's. Next valid mask number is " + next);
            }
        }
        if (valid == false)
            return valid;
        txtOctet1.setBackground(Color.WHITE);
        txtOctet2.setBackground(Color.WHITE);
        txtOctet3.setBackground(Color.WHITE);
        txtOctet4.setBackground(Color.WHITE);
        txtMaskP1.setBackground(Color.WHITE);
        txtMaskP2.setBackground(Color.WHITE);
        txtMaskP3.setBackground(Color.WHITE);
        txtMaskP4.setBackground(Color.WHITE);
        txtMaskS1.setBackground(Color.WHITE);
        txtMaskS2.setBackground(Color.WHITE);
        txtMaskS3.setBackground(Color.WHITE);
        txtMaskS4.setBackground(Color.WHITE);
        return valid;
    }

    private boolean validateMask(int num) {
        boolean valid = true;
        switch (num) {
            case 0: break;
            case 128: break;
            case 192: break;
            case 224: break;
            case 240: break;
            case 248: break;
            case 252: break;
            case 254: break;
            case 255: break;
            default: valid = false;
                if (num < 128) {
                    next = 128;
                } else if (num < 192) {
                    next = 192;
                } else if (num < 224) {
                    next = 224;
                } else if (num < 240) {
                    next = 240;
                } else if (num < 248) {
                    next = 248;
                } else if (num < 252) {
                    next = 252;
                } else if (num < 254) {
                    next = 254;
                } else if (num < 255) {
                    next = 255;
                }
                break;
            }
        return valid;
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnReset;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBOctets;
    private javax.swing.JLabel lblBin1;
    private javax.swing.JLabel lblBin2;
    private javax.swing.JLabel lblBin3;
    private javax.swing.JLabel lblBin4;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblErrorMsg;
    private javax.swing.JLabel lblIPAddr;
    private javax.swing.JLabel lblMask1;
    private javax.swing.JLabel lblMask2;
    private javax.swing.JLabel lblMask3;
    private javax.swing.JLabel lblMask4;
    private javax.swing.JLabel lblPBin1;
    private javax.swing.JLabel lblPBin2;
    private javax.swing.JLabel lblPBin3;
    private javax.swing.JLabel lblPBin4;
    private javax.swing.JLabel lblPNetmask;
    private javax.swing.JLabel lblPrimaryNetmask;
    private javax.swing.JLabel lblSBin1;
    private javax.swing.JLabel lblSBin2;
    private javax.swing.JLabel lblSBin3;
    private javax.swing.JLabel lblSBin4;
    private javax.swing.JLabel lblSlashClass;
    private javax.swing.JLabel lblSlashIP;
    private javax.swing.JLabel lblSlashPrimary;
    private javax.swing.JLabel lblSlashSubnet;
    private javax.swing.JLabel lblSubnetmask1;
    private javax.swing.JLabel lblSubnetmask2;
    private javax.swing.JTextField txtMaskP1;
    private javax.swing.JTextField txtMaskP2;
    private javax.swing.JTextField txtMaskP3;
    private javax.swing.JTextField txtMaskP4;
    private javax.swing.JTextField txtMaskS1;
    private javax.swing.JTextField txtMaskS2;
    private javax.swing.JTextField txtMaskS3;
    private javax.swing.JTextField txtMaskS4;
    private javax.swing.JTextField txtOctet1;
    private javax.swing.JTextField txtOctet2;
    private javax.swing.JTextField txtOctet3;
    private javax.swing.JTextField txtOctet4;
    // End of variables declaration//GEN-END:variables


}
